name: Swift

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" && swift build -v
      - name: Run tests
        run: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" && swift test -v
